=begin
Report Generator API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'DELETE', '/paragraphs/{id}', controller_name: 'paragraphs', action_name: 'destroy'
  add_openapi_route 'PATCH', '/paragraphs/{id}', controller_name: 'paragraphs', action_name: 'update'
  add_openapi_route 'POST', '/paragraphs', controller_name: 'paragraphs', action_name: 'create'
  add_openapi_route 'GET', '/reports', controller_name: 'reports', action_name: 'index'
  add_openapi_route 'GET', '/reports/{id}', controller_name: 'reports', action_name: 'show'
  add_openapi_route 'POST', '/reports', controller_name: 'reports', action_name: 'create'
  add_openapi_route 'POST', '/sessions', controller_name: 'sessions', action_name: 'create'
  add_openapi_route 'DELETE', '/sessions', controller_name: 'sessions', action_name: 'delete_session'
  add_openapi_route 'POST', '/users', controller_name: 'users', action_name: 'create'
end
